"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, BellSimpleIcon, CheckCircleIcon, PlusIcon } from "@phosphor-icons/react/dist/ssr";
import { isTightsProduct, type CatalogProduct } from "@/lib/tights";
import { useFitState } from "@/lib/fit-state";
import type { LiveCatalogStatus } from "@/lib/live-catalog";

export function PassportClient({ catalog, catalogStatus }: { catalog: CatalogProduct[]; catalogStatus: LiveCatalogStatus }) {
  const { passport, wearEvents, updatePassportState } = useFitState();
  const items = passport.map((item) => ({ item, product: catalog.find((product) => product.id === item.productId) })).filter((entry): entry is { item: typeof passport[number]; product: CatalogProduct } => Boolean(entry.product));
  const bras = items.filter(({ product }) => !isTightsProduct(product)).length;
  const tights = items.filter(({ product }) => isTightsProduct(product)).length;
  return <>
    <section className="passport-overview"><div><p className="eyebrow">My Passport</p><h1>The products you’ve tried, saved and learned from.</h1><p>Your Passport is a private reference, not a social feed. It keeps bras and tights in the same useful product memory without turning your body or purchase history into a score.</p></div><div className="passport-numbers"><div><strong>{items.length}</strong><span>products saved</span></div><div><strong>{bras} / {tights}</strong><span>bras / tights</span></div><div><strong>{wearEvents.filter((event) => event.wouldWearAgain === "yes").length || "—"}</strong><span>repeat signals</span></div></div></section>
    {items.length ? <section className="passport-list">{items.map(({ item, product }) => { const wears = wearEvents.filter((event) => event.productId === product.id); const tightsProduct = isTightsProduct(product); return <article key={product.id}><div className="passport-image"><Image src={tightsProduct ? "/images/perfectpair-tights-category.png" : "/images/perfectpair-bra-category.png"} alt="" fill sizes="52px" /></div><div><p className="eyebrow">{tightsProduct ? "Tights · " : "Bras · "}{product.brand}</p><h2>{product.name}</h2><p>{tightsProduct ? `${product.denier} denier · ${wears.length ? `${wears.length} saved outcome${wears.length === 1 ? "" : "s"}` : "No diary entry yet"}` : `${product.style.replace("_", " ")} · ${wears.length ? `${wears.length} logged fit check${wears.length === 1 ? "" : "s"}` : "No fit check yet"}`}</p></div><select aria-label={`Passport state for ${product.name}`} value={item.state} onChange={(event) => updatePassportState(product.id, event.target.value as typeof item.state)}><option value="want_to_try">Want to try</option><option value="owned">Owned</option><option value="repurchase">Repurchase</option><option value="retired">Retired</option></select><div className="passport-actions"><Link href={`/products/${product.slug}`}>Open research <ArrowRightIcon size={14} /></Link><span><BellSimpleIcon size={14} /> Alert model ready</span></div></article>; })}</section> : <section className="passport-empty"><CheckCircleIcon size={29} weight="regular" /><h2>Your Passport is ready.</h2><p>{catalogStatus === "ready" ? "Save a bra or pair of tights from the research library. The first entry becomes part of a private, useful product history." : "The live research library is still being built. When the first reviewed product is published, you can save it here."}</p><Link className="button" href="/discover"><PlusIcon size={15} /> {catalogStatus === "ready" ? "Find a product to save" : "View catalogue status"}</Link></section>}
    <section className="passport-principle"><p className="eyebrow">Product memory, not body scoring</p><h2>The point is a better next choice.</h2><p>PerfectPair does not score bodies or appearance. It remembers consented product outcomes so the next shortlist can be more honest and specific.</p><Link className="text-button" href="/discover">Open live catalogue <ArrowRightIcon size={14} /></Link></section>
  </>;
}
