"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, BellSimpleIcon, CheckCircleIcon, PlusIcon } from "@phosphor-icons/react/dist/ssr";
import { useI18n } from "@/components/lang-provider";
import { isTightsProduct, type CatalogProduct } from "@/lib/tights";
import { useFitState } from "@/lib/fit-state";
import type { LiveCatalogStatus } from "@/lib/live-catalog";

export function PassportClient({ catalog, catalogStatus }: { catalog: CatalogProduct[]; catalogStatus: LiveCatalogStatus }) {
  const { t, term } = useI18n();
  const { passport, wearEvents, updatePassportState } = useFitState();
  const items = passport.map((item) => ({ item, product: catalog.find((product) => product.id === item.productId) })).filter((entry): entry is { item: typeof passport[number]; product: CatalogProduct } => Boolean(entry.product));
  const bras = items.filter(({ product }) => !isTightsProduct(product)).length;
  const tights = items.filter(({ product }) => isTightsProduct(product)).length;
  const ready = catalogStatus === "ready";
  return <>
    <section className="passport-overview"><div><p className="eyebrow">{t("My Passport", "我的试穿册")}</p><h1>{t("The products you’ve tried, saved and learned from.", "你试过、收藏过、从中学到经验的产品。")}</h1><p>{t("Your Passport is a private reference, not a social feed. It keeps bras and tights in the same useful product memory without turning your body or purchase history into a score.", "试穿册是你的私人参考，不是社交动态。内衣和丝袜都记在这里，但不会把你的身材或购物记录变成分数。")}</p></div><div className="passport-numbers"><div><strong>{items.length}</strong><span>{t("products saved", "件已收藏")}</span></div><div><strong>{bras} / {tights}</strong><span>{t("bras / tights", "内衣 / 丝袜")}</span></div><div><strong>{wearEvents.filter((event) => event.wouldWearAgain === "yes").length || "—"}</strong><span>{t("repeat signals", "还会再穿")}</span></div></div></section>
    {items.length ? <section className="passport-list">{items.map(({ item, product }) => { const wears = wearEvents.filter((event) => event.productId === product.id); const tightsProduct = isTightsProduct(product); return <article key={product.id}><div className="passport-image"><Image src={tightsProduct ? "/images/perfectpair-tights-category.png" : "/images/perfectpair-bra-category.png"} alt="" fill sizes="52px" /></div><div><p className="eyebrow">{tightsProduct ? t("Tights · ", "丝袜 · ") : t("Bras · ", "内衣 · ")}{product.brand}</p><h2>{product.name}</h2><p>{tightsProduct ? `${t(`${product.denier} denier`, `${product.denier}D`)} · ${wears.length ? t(`${wears.length} saved outcome${wears.length === 1 ? "" : "s"}`, `${wears.length} 条穿着记录`) : t("No diary entry yet", "还没有日记")}` : `${term(product.style)} · ${wears.length ? t(`${wears.length} logged fit check${wears.length === 1 ? "" : "s"}`, `${wears.length} 次试穿记录`) : t("No fit check yet", "还没有试穿记录")}`}</p></div><select aria-label={t(`Passport state for ${product.name}`, `${product.name} 的状态`)} value={item.state} onChange={(event) => updatePassportState(product.id, event.target.value as typeof item.state)}><option value="want_to_try">{t("Want to try", "想试试")}</option><option value="owned">{t("Owned", "已拥有")}</option><option value="repurchase">{t("Repurchase", "会回购")}</option><option value="retired">{t("Retired", "不再穿")}</option></select><div className="passport-actions"><Link href={`/products/${product.slug}`}>{t("Open research", "查看资料")} <ArrowRightIcon size={14} /></Link><span><BellSimpleIcon size={14} /> {t("Alert model ready", "提醒功能已就绪")}</span></div></article>; })}</section> : <section className="passport-empty"><CheckCircleIcon size={29} weight="regular" /><h2>{t("Your Passport is ready.", "你的试穿册准备好了。")}</h2><p>{ready ? t("Save a bra or pair of tights from the research library. The first entry becomes part of a private, useful product history.", "从产品库收藏一件内衣或一双丝袜，它会成为你私人产品记录的第一条。") : t("The live research library is still being built. When the first reviewed product is published, you can save it here.", "产品库还在建设中。第一款审核过的产品发布后，就能收藏到这里。")}</p><Link className="button" href="/discover"><PlusIcon size={15} /> {ready ? t("Find a product to save", "去找产品收藏") : t("View catalogue status", "查看产品库进度")}</Link></section>}
    <section className="passport-principle"><p className="eyebrow">{t("Product memory, not body scoring", "记住产品，不给身材打分")}</p><h2>{t("The point is a better next choice.", "目的就是下一次选得更好。")}</h2><p>{t("PerfectPair does not score bodies or appearance. It remembers consented product outcomes so the next shortlist can be more honest and specific. If an eligible outerwear item still misses, prepare a private external-listing draft instead of handling money here.", "PerfectPair 不给身材或外貌打分，只记住你同意保存的产品体验，让下一份候选清单更真实、更具体。符合条件的外穿衣物如果还是不合适，可以准备一份私人草稿拿到外部平台转让，这里不经手任何钱款。")}</p><div className="passport-principle-actions"><Link className="text-button" href="/discover">{t("Open live catalogue", "打开产品库")} <ArrowRightIcon size={14} /></Link><Link className="text-button" href="/pass-it-forward">{t("Pass it forward", "转给下一位")} <ArrowRightIcon size={14} /></Link></div></section>
  </>;
}
