"use client";

import { CheckCircleIcon, ClockCounterClockwiseIcon, CaretDownIcon, LockKeyIcon } from "@phosphor-icons/react/dist/ssr";
import { useEffect, useRef, useState } from "react";
import { useI18n } from "@/components/lang-provider";
import { ProfileReadiness } from "@/components/profile-readiness";
import { useFitState } from "@/lib/fit-state";
import type { BraOccasion, BraProfile, FitIssue } from "@/lib/types";

const priorities: BraProfile["fitPriorities"] = ["comfort", "support", "band", "cup", "wire", "straps", "breathability", "durability", "value"];
const occasions: Array<{ id: BraOccasion; en: string; zh: string }> = [
  { id: "everyday", en: "Everyday", zh: "日常" }, { id: "work", en: "Work", zh: "上班" }, { id: "lounge", en: "Lounge", zh: "居家" }, { id: "occasion", en: "Occasion", zh: "正式场合" }, { id: "travel", en: "Travel", zh: "旅行" }, { id: "exercise", en: "Exercise", zh: "运动" },
];
const issues: Array<{ id: FitIssue; en: string; zh: string }> = [
  { id: "band_digs", en: "Band digs", zh: "下围勒" }, { id: "band_rides_up", en: "Band rides up", zh: "下围往上跑" }, { id: "cup_spillage", en: "Cup spillage", zh: "罩杯溢出" }, { id: "cup_gaping", en: "Cup gaping", zh: "罩杯空杯" }, { id: "wire_pokes", en: "Wire pokes", zh: "钢圈戳人" }, { id: "wire_on_tissue", en: "Wire sits on tissue", zh: "钢圈压到胸" }, { id: "straps_slip", en: "Straps slip", zh: "肩带滑落" }, { id: "straps_dig", en: "Straps dig", zh: "肩带勒" }, { id: "gore_floats", en: "Center doesn’t sit flat", zh: "中间鸡心不贴身" }, { id: "side_spillage", en: "Side spillage", zh: "侧边溢出" }, { id: "cups_shift", en: "Cups shift", zh: "罩杯移位" },
];

export function ProfileForm() {
  const { t, term, date } = useI18n();
  const { profile: savedProfile, snapshots, saveProfile, privacy, hydrated } = useFitState();
  const [profile, setProfile] = useState<BraProfile>(savedProfile);
  const [saved, setSaved] = useState(false);
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const receivedHydratedProfile = useRef(false);
  useEffect(() => {
    if (!hydrated || receivedHydratedProfile.current) return;
    const sync = window.setTimeout(() => { setProfile(savedProfile); receivedHydratedProfile.current = true; }, 0);
    return () => window.clearTimeout(sync);
  }, [hydrated, savedProfile]);
  const update = <K extends keyof BraProfile>(key: K, value: BraProfile[K]) => { setSaved(false); setProfile((previous) => ({ ...previous, [key]: value })); };
  const togglePriority = (priority: BraProfile["fitPriorities"][number]) => setProfile((current) => ({ ...current, fitPriorities: current.fitPriorities.includes(priority) ? current.fitPriorities.filter((item) => item !== priority) : [...current.fitPriorities, priority] }));
  const toggleIssue = (issue: FitIssue) => setProfile((current) => ({ ...current, avoid: current.avoid.includes(issue) ? current.avoid.filter((item) => item !== issue) : [...current.avoid, issue] }));
  const toggleOccasion = (occasion: BraOccasion) => setProfile((current) => ({ ...current, commonUseCases: current.commonUseCases.includes(occasion) ? current.commonUseCases.filter((item) => item !== occasion) : [...current.commonUseCases, occasion] }));
  const number = (key: "currentBandSize" | "underbustSnugCm" | "underbustLooseCm" | "bustStandingCm" | "bustLeaningCm") => (event: React.ChangeEvent<HTMLInputElement>) => update(key, event.target.value === "" ? undefined : Number(event.target.value));
  const notSure = t("Not sure", "不确定");
  const noPreference = t("No preference", "没有偏好");
  const optionalModel = t("Optional brand / model / size", "可选：品牌 / 型号 / 尺码");

  return <div className="profile-layout"><form className="profile-form" onSubmit={(event) => { event.preventDefault(); saveProfile({ ...profile, profileMatchingConsent: privacy.anonymousMatching }, "My bra fit profile"); setSaved(true); }}>
    <ProfileReadiness category="bra" profile={profile} />
    <section><div className="form-section-heading"><span className="step">01</span><div><h2>{t("Start with what you know", "从你知道的开始")}</h2><p>{t("Choose one route: a familiar size or a bra that works. Nothing is required, and you can refine only when a recommendation needs it.", "二选一就行：一个熟悉的尺码，或一件穿着合适的内衣。什么都不是必填，需要时再补充。")}</p></div></div>
      <div className="fields three"><label>{t("Size system", "尺码体系")}<select value={profile.sizeSystem ?? "unknown"} onChange={(event) => update("sizeSystem", event.target.value as BraProfile["sizeSystem"])}><option value="unknown">{notSure}</option><option value="US_CA">{t("US / Canada", "美国 / 加拿大")}</option><option value="UK">{t("UK", "英国")}</option><option value="EU">{t("EU", "欧洲")}</option><option value="AU_NZ">{t("Australia / NZ", "澳洲 / 新西兰")}</option><option value="brand_specific">{t("Brand-specific", "品牌自有尺码")}</option></select></label><label>{t("Current band size", "目前下围尺码")}<input type="number" min="24" max="54" value={profile.currentBandSize ?? ""} onChange={number("currentBandSize")} placeholder={t("e.g. 34", "例如 34")} /></label><label>{t("Current cup size", "目前罩杯")}<input value={profile.currentCupSize ?? ""} onChange={(event) => update("currentCupSize", event.target.value.toUpperCase())} placeholder={t("e.g. D", "例如 D")} /></label></div>
      <div className="fields three"><label>{t("A bra that works", "一件穿着合适的内衣")}<input value={profile.knownWorkingBra ?? ""} onChange={(event) => update("knownWorkingBra", event.target.value)} placeholder={optionalModel} /></label><label>{t("Wire preference", "钢圈偏好")}<select value={profile.preferredWire ?? "any"} onChange={(event) => update("preferredWire", event.target.value as BraProfile["preferredWire"])}><option value="any">{noPreference}</option><option value="underwire">{t("Underwire", "钢圈")}</option><option value="flex_wire">{t("Flex wire", "软钢圈")}</option><option value="wireless">{t("Wire-free", "无钢圈")}</option></select></label><div className="profile-field-note"><LockKeyIcon size={15} /><span><b>{t("Private by default", "默认私密")}</b><small>{t("These details are used only for your own match unless you separately enable anonymous contribution.", "这些信息只用来给你自己做匹配，除非你另外打开匿名分享。")}</small></span></div></div>
    </section>
    <section><div className="form-section-heading"><span className="step">02</span><div><h2>{t("What should improve?", "希望哪里更好？")}</h2><p>{t("Pick only one or two. Practical experience is more useful than a long questionnaire.", "选一两个就好。实际感受比一长串问卷更有用。")}</p></div></div>
      <p className="chip-label">{t("Where will you wear it?", "在什么场合穿？")}</p><div className="chips">{occasions.map((occasion) => <button className={`chip ${profile.commonUseCases.includes(occasion.id) ? "selected" : ""}`} type="button" onClick={() => toggleOccasion(occasion.id)} key={occasion.id}>{t(occasion.en, occasion.zh)}</button>)}</div>
      <p className="chip-label">{t("What matters most", "最在意什么")}</p><div className="chips">{priorities.map((priority) => <button className={`chip ${profile.fitPriorities.includes(priority) ? "selected" : ""}`} type="button" onClick={() => togglePriority(priority)} key={priority}>{term(priority)}</button>)}</div>
      <p className="chip-label">{t("Problems to avoid", "想避免的问题")}</p><div className="chips">{issues.map((issue) => <button className={`chip ${profile.avoid.includes(issue.id) ? "selected" : ""}`} type="button" onClick={() => toggleIssue(issue.id)} key={issue.id}>{t(issue.en, issue.zh)}</button>)}</div>
    </section>
    <section className="optional-profile-section"><button type="button" className="optional-disclosure" aria-expanded={advancedOpen} onClick={() => setAdvancedOpen((open) => !open)}><span><span className="step">03</span><span><b>{t("Improve a specific match", "让匹配更精准")}</b><small>{t("Optional details, only if you want a more precise starting size or construction check.", "可选。想要更准的起步尺码或版型核对时再填。")}</small></span></span><CaretDownIcon className={advancedOpen ? "turned" : ""} size={17} /></button>
      {advancedOpen && <div className="optional-profile-body"><p className="optional-profile-note">{t("Measurements are manually entered, never inferred from a photo or scan. “Not sure” is always a valid answer.", "尺寸都是你自己填的，绝不会从照片或扫描推算。“不确定”也是完全可以的答案。")}</p>
        <div className="fields three"><label>{t("Snug underbust", "下胸围（贴身）")} <span>cm</span><input type="number" value={profile.underbustSnugCm ?? ""} onChange={number("underbustSnugCm")} /></label><label>{t("Standing bust", "上胸围（站立）")} <span>cm</span><input type="number" value={profile.bustStandingCm ?? ""} onChange={number("bustStandingCm")} /></label><label>{t("How certain is this?", "有多确定？")}<select value={profile.measurementConfidence ?? "not_sure"} onChange={(event) => update("measurementConfidence", event.target.value as BraProfile["measurementConfidence"])}><option value="not_sure">{notSure}</option><option value="measured_recently">{t("Measured recently", "最近量过")}</option><option value="estimated">{t("Estimated", "估计的")}</option></select></label></div>
        <div className="fields three"><label>{t("Loose underbust", "下胸围（放松）")} <span>{t("cm · optional", "cm · 可选")}</span><input type="number" value={profile.underbustLooseCm ?? ""} onChange={number("underbustLooseCm")} /></label><label>{t("Leaning bust", "上胸围（前倾）")} <span>{t("cm · optional", "cm · 可选")}</span><input type="number" value={profile.bustLeaningCm ?? ""} onChange={number("bustLeaningCm")} /></label><label>{t("A bra that does not work", "一件不合适的内衣")}<input value={profile.knownProblemBra ?? ""} onChange={(event) => update("knownProblemBra", event.target.value)} placeholder={optionalModel} /></label></div>
        <div className="fields three"><label>{t("Root width", "胸根宽度")}<select value={profile.rootWidth ?? "unknown"} onChange={(event) => update("rootWidth", event.target.value as BraProfile["rootWidth"])}><option value="unknown">{notSure}</option><option value="narrow">{t("Narrow", "窄")}</option><option value="average">{t("Average", "一般")}</option><option value="wide">{t("Wide", "宽")}</option></select></label><label>{t("Projection", "胸型饱满度")}<select value={profile.projection ?? "unknown"} onChange={(event) => update("projection", event.target.value as BraProfile["projection"])}><option value="unknown">{notSure}</option><option value="shallow">{t("Shallow", "偏平")}</option><option value="average">{t("Average", "一般")}</option><option value="projected">{t("Projected", "饱满")}</option></select></label><label>{t("Strap placement", "肩带位置")}<select value={profile.strapPlacementPreference ?? "any"} onChange={(event) => update("strapPlacementPreference", event.target.value as BraProfile["strapPlacementPreference"])}><option value="any">{noPreference}</option><option value="centered">{t("More centred", "偏中间")}</option><option value="wide_set">{t("Wider set", "偏两侧")}</option></select></label></div>
        <label className="change-check"><input type="checkbox" checked={Boolean(profile.fitChangedRecently)} onChange={(event) => update("fitChangedRecently", event.target.checked)} /><span><b>{t("My fit feels different lately", "最近感觉尺码变了")}</b><small>{t("We will treat older size references more cautiously. You never need to say why.", "我们会更谨慎地参考旧尺码。你不需要说明原因。")}</small></span></label>
      </div>}
    </section>
    <div className="form-actions"><p><LockKeyIcon size={14} /> {t("No photo upload, body scan, appearance score, health reason or public profile. You can update or clear these fields whenever you choose.", "不上传照片、不做身体扫描、不评价外貌、不问健康原因、没有公开主页。你随时可以修改或清空。")}</p><button className="button" type="submit">{saved ? <><CheckCircleIcon size={16} /> {t("Saved to your timeline", "已存到你的时间线")}</> : t("Save My Bra Profile", "保存我的内衣档案")}</button></div>
  </form>
  <aside className="timeline-card"><p className="eyebrow"><ClockCounterClockwiseIcon size={13} /> {t("Fit timeline", "尺码时间线")}</p><h3>{hydrated ? t(`${snapshots.length} saved fit ${snapshots.length === 1 ? "record" : "records"}`, `已保存 ${snapshots.length} 条尺码记录`) : t("Loading your timeline", "正在读取时间线")}</h3><p>{t("Fit changes are normal. A new snapshot updates future matches while keeping past wears and reviews honest.", "尺码变化很正常。新的记录会更新之后的匹配，过去的试穿和点评保持原样。")}</p><div className="timeline-list">{snapshots.slice(0, 4).map((snapshot, index) => <div key={snapshot.id}><span className="timeline-dot"></span><strong>{index === 0 ? t("Current bra fit", "目前的内衣尺码") : t(snapshot.label || "Saved fit", "已保存的尺码")}</strong><small>{date(snapshot.recordedAt)} · {snapshot.profile.currentBandSize ?? "—"}{snapshot.profile.currentCupSize ?? ""} · {snapshot.profile.preferredWire && snapshot.profile.preferredWire !== "any" ? term(snapshot.profile.preferredWire) : term("any wire")}</small></div>)}</div></aside>
  </div>;
}
