-- Brand-source onboarding is separate from live ingestion. Every listed brand
-- is a coverage target, not a claim that PerfectPair already has permission to
-- copy its catalogue. Credentials must live in a secrets manager, never here.

create table if not exists public.brand_source_targets (
  id text primary key,
  brand_name text not null,
  categories text[] not null check (cardinality(categories) > 0 and categories <@ array['bra', 'tights']),
  launch_wave integer not null check (launch_wave in (1, 2)),
  status text not null default 'awaiting_authorized_access' check (status in ('awaiting_authorized_access', 'evidence_collection', 'rights_review', 'feed_validation', 'ready_for_review', 'active', 'paused')),
  channel_order text[] not null default array['brand_claim_portal', 'retailer_or_distributor_feed', 'pim_or_gdsn_licensed_data', 'brand_provided_csv', 'physical_sample_audit', 'verified_contributor_evidence'],
  required_facts text[] not null,
  excluded_without_written_licence text[] not null,
  accountable_owner text,
  next_action text not null default 'Open a brand-claim record and collect either licensed commercial data or independent fit evidence; do not crawl public product pages.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_name, categories)
);

create table if not exists public.brand_source_submissions (
  id uuid primary key default gen_random_uuid(),
  brand_target_id text not null references public.brand_source_targets(id) on delete cascade,
  source_id uuid references public.ingestion_sources(id) on delete set null,
  channel text not null check (channel in ('brand_claim_portal', 'retailer_or_distributor_feed', 'pim_or_gdsn_licensed_data', 'brand_provided_csv', 'physical_sample_audit', 'verified_contributor_evidence')),
  status text not null default 'identified' check (status in ('identified', 'contact_ready', 'access_requested', 'access_granted', 'rights_review', 'sample_received', 'validated', 'rejected', 'paused')),
  partner_reference text,
  terms_url text,
  permission_scope text,
  evidence_reference text,
  requested_fields text[] not null default '{}',
  granted_fields text[] not null default '{}',
  licence_expiry_at timestamptz,
  last_checked_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists brand_source_submissions_target_status_idx
  on public.brand_source_submissions(brand_target_id, status);

insert into public.brand_source_targets (id, brand_name, categories, launch_wave, required_facts, excluded_without_written_licence) values
  ('bra-aerie', 'Aerie', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-anita', 'Anita', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-bravissimo', 'Bravissimo', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-chantelle', 'Chantelle', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-curvy-kate', 'Curvy Kate', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-elomi', 'Elomi', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-evelyn-bobbie', 'Evelyn & Bobbie', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-felina', 'Felina', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-fantasie', 'Fantasie', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-freya', 'Freya', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-glamorise', 'Glamorise', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-harper-wilde', 'Harper Wilde', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-knix', 'Knix', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-le-mystere', 'Le Mystère', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-natori', 'Natori', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-panache', 'Panache', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-parfait', 'Parfait', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-primadonna', 'PrimaDonna', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-savage-x-fenty', 'Savage X Fenty', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-soma', 'Soma', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-thirdlove', 'ThirdLove', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-understance', 'Understance', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-wacoal', 'Wacoal', array['bra'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-warner-s', 'Warner''s', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-victoria-s-secret', 'Victoria''s Secret', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('bra-empreinte', 'Empreinte', array['bra'], 2, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','style','wire','cupConstruction','supportLevel','material','sizeSystem','sizeChartVersion','sizeRange','bandRange','cupRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-commando', 'Commando', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-falke', 'Falke', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-heist', 'Heist', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-sheertex', 'Sheertex', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-spanx', 'Spanx', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text']),
  ('tights-wolford', 'Wolford', array['tights'], 1, array['brand','productFamily','productName','merchantSku','canonicalProductUrl','variantId','denier','opacity','waist','toe','compression','material','sizeSystem','sizeChartVersion','sizeRange','price','currency','availability','countryOrMarket','lastUpdatedAt'], array['product images and image URLs','long product descriptions','brand editorial copy','logos and other creative assets','merchant review text'])
on conflict (id) do nothing;

alter table public.brand_source_targets enable row level security;
alter table public.brand_source_submissions enable row level security;

create trigger brand_source_targets_updated_at before update on public.brand_source_targets
  for each row execute procedure public.set_updated_at();
create trigger brand_source_submissions_updated_at before update on public.brand_source_submissions
  for each row execute procedure public.set_updated_at();

comment on table public.brand_source_targets is 'Every directory brand that must receive an authorised product-data source before publication.';
comment on table public.brand_source_submissions is 'Evidence-led onboarding trail for brand, affiliate or authorised retailer data channels. Never stores secrets.';
